// build.js — bundle the whole app into a single self-contained standalone.html.
//
// ES-module `import` doesn't work over file://, so to make the app openable by
// just double-clicking, we inline every module and the CSS into one HTML file.
// We concatenate the modules in dependency order, strip their import/export
// keywords (they all share one scope once inlined), and wrap them in a single
// IIFE so behaviour matches the modular build exactly.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(root, p), 'utf8');

// Dependency order: elements first (everything imports it), main last.
const MODULES = ['elements', 'simulation', 'renderer', 'input', 'ui', 'main'];

function bundleModules() {
  return MODULES.map((name) => {
    let code = read(`src/${name}.js`);
    code = code.replace(/import\b[^;]*?;/gs, ''); // drop import statements
    code = code.replace(/^export\s+/gm, '');      // drop the `export` keyword
    return `// ===== src/${name}.js =====\n${code.trim()}\n`;
  }).join('\n');
}

function build() {
  const css = read('src/styles.css');
  let html = read('index.html');

  // Inline the stylesheet.
  html = html.replace(
    /<link rel="stylesheet" href="src\/styles\.css" \/>/,
    `<style>\n${css}\n</style>`
  );

  // Inline the bundled script in place of the module entry point.
  const bundle = bundleModules();
  html = html.replace(
    /<script type="module" src="src\/main\.js"><\/script>/,
    `<script>\n(function () {\n'use strict';\n${bundle}\n})();\n</script>`
  );

  // Mark it as generated so nobody hand-edits it.
  html = html.replace(
    '<head>',
    '<head>\n  <!-- GENERATED by build.js from index.html + src/*. Do not edit by hand; run `npm run build`. -->'
  );

  writeFileSync(join(root, 'standalone.html'), html);
  const kb = (Buffer.byteLength(html) / 1024).toFixed(1);
  console.log(`  ✓ wrote standalone.html (${kb} KB) — open it directly in any browser, no server needed.`);
}

build();
